version: 2

build:
<<<<<<<
  apt_packages:
    - graphviz
  os: ubuntu-22.04
=======
  os: ubuntu-lts-latest
>>>>>>>
  tools:
    python: "mambaforge-latest"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    pre_install:
      - git update-index --assume-unchanged .rtd-environment.yaml docs/conf.py

conda:
  environment: .rtd-environment.yaml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - htmlzip

python:
  install:
    - method: pip
      extra_requirements:
        - docs
      path: .
