version: 2

build:
  apt_packages:
    - graphviz
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:

    post_checkout:
      - git fetch --unshallow || true
    pre_install:
      - git update-index --assume-unchanged .rtd-environment.yml docs/conf.py

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      extra_requirements:
        - all
        - docs
      path: .
